# Generated by Django 4.0.4 on 2022-04-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='is_legitimate',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
